import { SKPRecord } from './types';

export const MOCK_SKP_DATA: SKPRecord[] = [
  {
    id: '1',
    nip: '198501012010011001',
    namaPegawai: 'Ahmad Subarjo',
    jabatan: 'Analis Kepegawaian Ahli Madya',
    unitKerja: 'Sekretariat BSKJI',
    tahun: 2024,
    periode: 'Tahunan',
    jenisDokumen: ['Sasaran Kinerja Pegawai', 'Hasil Evaluasi Kinerja Pegawai Hasil Kerja Kuantitatif Tahunan'],
    status: 'Sudah Diambil',
    pengambil: 'Siti Aminah',
    unitKerjaPengambil: 'P2SI',
    tanggalAmbil: '2024-03-15T10:30:00Z',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'SKP_Ahmad_Subarjo_2024.pdf',
  },
  {
    id: '2',
    nip: '199005122015032005',
    namaPegawai: 'Budi Santoso',
    jabatan: 'Pranata Komputer Ahli Pertama',
    unitKerja: 'P4SI',
    tahun: 2024,
    periode: 'Triwulan I',
    jenisDokumen: ['Evaluasi Kinerja Pegawai'],
    status: 'Belum Diambil',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'SKP_Budi_Santoso_2024_Q1.pdf',
  },
  {
    id: '3',
    nip: '198802142012121003',
    namaPegawai: 'Citra Lestari',
    jabatan: 'Bendahara Pengeluaran',
    unitKerja: 'POPTIKJI',
    tahun: 2024,
    periode: 'Tahunan',
    jenisDokumen: ['Sasaran Kinerja Pegawai'],
    status: 'Sudah Diambil',
    pengambil: 'Citra Lestari',
    unitKerjaPengambil: 'POPTIKJI',
    tanggalAmbil: '2024-03-20T09:15:00Z',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'SKP_Citra_Lestari_2024.pdf',
  },
  {
    id: '4',
    nip: '199207202018012001',
    namaPegawai: 'Dedi Kurniawan',
    jabatan: 'Pengelola Barang Milik Negara',
    unitKerja: 'PIH',
    tahun: 2024,
    periode: 'Triwulan II',
    jenisDokumen: ['Evaluasi Kinerja Pegawai'],
    status: 'Belum Diambil',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'SKP_Dedi_Kurniawan_2024_Q2.pdf',
  },
  {
    id: '5',
    nip: '198703052011011002',
    namaPegawai: 'Eka Putri',
    jabatan: 'Analis Perencanaan',
    unitKerja: 'BBSPJIKFK',
    tahun: 2024,
    periode: 'Triwulan III',
    jenisDokumen: ['Evaluasi Kinerja Pegawai'],
    status: 'Sudah Diambil',
    pengambil: 'Fajar Ramadhan',
    unitKerjaPengambil: 'BBSPJIA',
    tanggalAmbil: '2024-03-22T14:45:00Z',
  },
  {
    id: '6',
    nip: '199510102020122004',
    namaPegawai: 'Gita Savitri',
    jabatan: 'Pranata Humas Ahli Pertama',
    unitKerja: 'BBSPJIBBT',
    tahun: 2024,
    periode: 'Tahunan',
    jenisDokumen: ['Sasaran Kinerja Pegawai'],
    status: 'Belum Diambil',
  },
  {
    id: '7',
    nip: '198212252008011005',
    namaPegawai: 'Hendra Wijaya',
    jabatan: 'Analis Organisasi',
    unitKerja: 'BBSPJIS',
    tahun: 2024,
    periode: 'Triwulan IV',
    jenisDokumen: ['Evaluasi Kinerja Pegawai'],
    status: 'Sudah Diambil',
    pengambil: 'Hendra Wijaya',
    unitKerjaPengambil: 'BBSPJIS',
    tanggalAmbil: '2024-03-25T11:00:00Z',
  },
  {
    id: '8',
    nip: '199304042019032002',
    namaPegawai: 'Indah Permata',
    jabatan: 'Analis Kerjasama',
    unitKerja: 'BBSPJILM',
    tahun: 2024,
    periode: 'Tahunan',
    jenisDokumen: ['Sasaran Kinerja Pegawai'],
    status: 'Belum Diambil',
  },
];

export const MOCK_PLT_DATA = [
  {
    id: 'plt-1',
    nip: '198501012010011001',
    namaPegawai: 'Ahmad Subarjo',
    jabatanAsli: 'Analis Kepegawaian Ahli Madya',
    jabatanPlt: 'Kepala Bagian Tata Usaha',
    unitKerja: 'Sekretariat BSKJI',
    noSk: 'SK/PLT/001/2024',
    tglMulai: '2024-01-01',
    tglSelesai: '2024-03-31',
    status: 'Selesai',
  },
  {
    id: 'plt-2',
    nip: '199005122015032005',
    namaPegawai: 'Budi Santoso',
    jabatanAsli: 'Pranata Komputer Ahli Pertama',
    jabatanPlt: 'Koordinator IT',
    unitKerja: 'P4SI',
    noSk: 'SK/PLT/002/2024',
    tglMulai: '2024-04-01',
    tglSelesai: '2024-06-30',
    status: 'Aktif',
  },
];

export const MOCK_PLH_DATA = [
  {
    id: 'plh-1',
    nip: '198802142012121003',
    namaPegawai: 'Citra Lestari',
    jabatanAsli: 'Bendahara Pengeluaran',
    jabatanPlh: 'Pejabat Pembuat Komitmen',
    unitKerja: 'POPTIKJI',
    noSk: 'SK/PLH/001/2024',
    tglMulai: '2024-03-10',
    tglSelesai: '2024-03-15',
    status: 'Selesai',
  },
];

export const JENIS_DOKUMEN_LIST = [
  'Sasaran Kinerja Pegawai',
  'Evaluasi Kinerja Pegawai',
  'Hasil Evaluasi Kinerja Pegawai Hasil Kerja Kuantitatif Tahunan',
];

export const PERIODE_LIST = [
  'Triwulan I',
  'Triwulan II',
  'Triwulan III',
  'Triwulan IV',
  'Tahunan',
];

export const UNIT_KERJA_LIST = [
  'Sekretariat BSKJI',
  'P2SI',
  'P4SI',
  'POPTIKJI',
  'PIH',
  'BBSPJIKFK',
  'BBSPJIA',
  'BBSPJIBBT',
  'BBSPJIS',
  'BBSPJILM',
  'BBSPJIKKP',
  'BBSPJIKB',
  'BBSPJPPI',
  'BBSPJIHPMM',
  'BSPJI Banda Aceh',
  'BSPJI Medan',
  'BSPJI Padang',
  'BSPJI Palembang',
  'BSPJI Bandar Lampung',
  'BSPJI Surabaya',
  'BSPJI Banjarbaru',
  'BSPJI Pontianak',
  'BSPJI Samarinda',
  'BSPJI Manado',
  'BSPJI Ambon',
  'BSPJI Jakarta',
  'BSPJI Pekanbaru',
];

export const RATING_HASIL_KERJA_LIST = [
  'Diatas Ekspektasi',
  'Sesuai Ekspektasi',
  'Dibawah Ekspektasi',
];

export const RATING_PERILAKU_LIST = [
  'Diatas Ekspektasi',
  'Sesuai Ekspektasi',
  'Dibawah Ekspektasi',
];

export const PREDIKAT_KINERJA_LIST = [
  'Sangat Baik',
  'Baik',
  'Butuh Perbaikan',
  'Kurang',
  'Sangat Kurang',
];

export const STATUS_PEGAWAI_LIST = [
  'PNS',
  'CPNS',
  'PPPK',
  'PPPK Paruh Waktu'
];
